/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MyCustomIcons {
  MyCustomIcons._();

  static const _kFontFam = 'MyCustomIcons';
  static const String? _kFontPkg = null;

  static const IconData action_required = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_fav = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData added_fav = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData all = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData analize = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData appointme = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baby = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag_1 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData balance = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bill = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData booking = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData closest = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData community = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comunity = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cosmetics = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coupon_1 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coupon = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData default_icon = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drop_menu = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData e_payment = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData face = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift_active = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift_1 = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gift = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gmail = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hide = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData high = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_active = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData language = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light_____selection_controls_2__radio___2_states_ = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData liked = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_2 = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_1 = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData low = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData membership = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_active = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_1 = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_2 = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_account = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData my_wallet = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData navigation = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData new_address = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData online = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phase1 = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phase3 = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prescriptions = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData purchases_1 = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData purchases_active = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData purchases = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rated = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recommended_this_product = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData recommended = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reservations = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schdual = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schedule = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_1 = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store_active = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData success = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified_clininc = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified_doctor_mini = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified_doctor = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified_inful = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified_pharmacy = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData win = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wishlist_active = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wishlist = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
